run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/stable-net/anvil-go

  misspell:
    locale: US

  staticcheck:
    checks:
      - all
      - -SA1019

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam

    - path: test/
      linters:
        - errcheck

    - linters:
        - errcheck
      text: "Error return value"
